[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear',
    'php artisan cache:clear'
]

[phases.deploy]
cmds = [
    'php artisan storage:link --force',
    'chmod -R 775 storage bootstrap/cache',
    'chmod -R 777 storage/app/public',
    'php artisan migrate --force',
    'php artisan db:seed --force',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
